# Tensors in Pytorch

This is the main multidimensional data structure used in pytorch to do its calculations. Even though pytorch supports numpy arrays they are not suitable for deep learning related works due to multiple problems. Tensors fix those problems by providing additional features such as distributed operations on multiple devices/machines, GPU operations support, computation graph support etc.

In [1]:
import torch

In [6]:
a = torch.ones((3, 2))  # Similar to numpy ones create a vector with 1 value to the given dimension.
a[2]  # We can access elements just as we access them in numpy

tensor([1., 1.])

Just like numpy, torch tensors are saved in memory as contiguous memory chunks. Which basically means CPU caching techniques, parrallel processing techniques can be applied easily.

In [7]:
b = torch.tensor([1,2,3,4,5,6,7,8,9])
b

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
points_2d = torch.tensor([[1,2],[3,4],[5,6]])
points_2d[1]

tensor([3, 4])

In [9]:
points_2d.shape # Just like numpy XD

torch.Size([3, 2])

It is worth noting that, all the indexing operations return a tensor object. But it does not mean torch creates a new tensor object for that.

In [11]:
points_2d[1,1] # Indexing the tensor

tensor(4)

Below includes example slicing operations for tensors.

In [12]:
points_2d[1:]

tensor([[3, 4],
        [5, 6]])

In [13]:
points_2d[1: , 0]

tensor([3, 5])

In [15]:
points_2d[None] # This is special, 
                    # it adds additional dimension around the data. 
                    # Similar to the `unsqueeze` function

tensor([[[1, 2],
         [3, 4],
         [5, 6]]])

In [22]:
torch.unsqueeze(points_2d, 0)

tensor([[[1, 2],
         [3, 4],
         [5, 6]]])

In torch we can give names to the the tensor dimensions(Experimental feature!). This is helpful in keeping track of dimensions throughout complex operations.

In [23]:
test_img = torch.rand((3, 25, 25))

In [24]:
test_img.refine_names(..., 'Channel', 'Height', 'Width')

c:\Users\ddsdi\.virtualenvs\Pytorch_-_Use_Case_Exploration-FSDBtUdB\lib\site-packages\torch\_tensor.py:905: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\c10/core/TensorImpl.h:1408.)
  return super(Tensor, self).refine_names(names)


tensor([[[0.5485, 0.5179, 0.3718,  ..., 0.3386, 0.7032, 0.0538],
         [0.8161, 0.4748, 0.1484,  ..., 0.2440, 0.2855, 0.6904],
         [0.8604, 0.7152, 0.5117,  ..., 0.4493, 0.3384, 0.6642],
         ...,
         [0.0402, 0.8522, 0.2582,  ..., 0.3640, 0.1131, 0.1111],
         [0.4787, 0.3820, 0.9931,  ..., 0.5017, 0.7539, 0.1426],
         [0.4462, 0.0910, 0.1155,  ..., 0.6020, 0.9075, 0.0931]],

        [[0.5188, 0.7891, 0.9740,  ..., 0.3745, 0.2788, 0.7585],
         [0.1483, 0.9685, 0.5006,  ..., 0.8362, 0.0375, 0.1448],
         [0.7215, 0.0814, 0.7408,  ..., 0.5229, 0.2238, 0.3893],
         ...,
         [0.8274, 0.1469, 0.4439,  ..., 0.6575, 0.4228, 0.7071],
         [0.3851, 0.8331, 0.9895,  ..., 0.6077, 0.5968, 0.5964],
         [0.3364, 0.1816, 0.0257,  ..., 0.9907, 0.1269, 0.1198]],

        [[0.4230, 0.3410, 0.4444,  ..., 0.2268, 0.0655, 0.3102],
         [0.7054, 0.6552, 0.7055,  ..., 0.6521, 0.8026, 0.0387],
         [0.9557, 0.2813, 0.8386,  ..., 0.5676, 0.3350, 0.

Python standard data types are not optimal for large numerical operations. 

1. They are objects.
2. Python lists are collections of objects which does not have contigious memory allocation.
3. Python interpreter is not optimal compared to more specialized compiled code.

Therefore just as numpy, cython torch tensors use ctype data or more efficient low level numerical data structures.

In tensor constructor we can pass the datatype using `dtype` parameter. Some of the possible values are as below.

* torch.float (float32)
* torch.double (float64)
* torch.int8
* torch.uint8
* torch.int
* torch.long (int64)
* torch.bool

In [27]:
torch.ones((5,5), dtype=torch.double)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], dtype=torch.float64)

In [28]:
torch.ones((5,5)).double()

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], dtype=torch.float64)

In [29]:
torch.ones((5,5)).to(torch.double)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], dtype=torch.float64)

For more details about the pytorch tensor usage refer the [documentation](http://pytorch.org/docs).

But as a general overview how tensors work under the hood is as follows.

- Theres a torch class named `torch.Storage`. This is a one dimensional array of numerical data type spread over a contigious memory space.
- Tensors are a type of view which utilizes this one dimensional data structure in a clever manner to provide fast and efficient indexes. (The indexing mechanism is kinda similar to how we can store a binary tree in a list.)

Because of that, underline memory is allocated once. But we can index, reshape very fast since we are only using views on top of actual data. Very Cool!